language: go
os: linux

cache:
  directories:
    - "$HOME/.cache/go-build"
    - "$HOME/gopath/pkg/mod"

env:
  global:
    - CODECLIMATE=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - GO111MODULE=on

go:
  - master
  - 1.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

jobs:
  allow_failures:
    - go: master

before_script:
  - make env deps-fetch
  - |
    if [[ $TRAVIS_GO_VERSION == 1.15* ]]; then
      curl -sL $CODECLIMATE > /home/travis/gopath/bin/cc-test-reporter
      chmod +x /home/travis/gopath/bin/cc-test-reporter
      cc-test-reporter before-build
    fi

script:
  - |
    if [[ $TRAVIS_GO_VERSION == 1.15* ]]; then
      make test-with-coverage
    else
      make test
    fi

after_script:
  - |
    if [[ $TRAVIS_GO_VERSION == 1.15* ]]; then
      sed -i "s|$(go list -m)/||g" c.out # https://github.com/codeclimate/test-reporter/issues/378
      cc-test-reporter after-build -t gocov -p $(go list -m) --exit-code $TRAVIS_TEST_RESULT
    fi

notifications:
  slack:
    secure: lOPtF0knN/LO7v02Ntm3cSmbcmA/Po6/ZJWdLcCVcdTfRA/TdsGvVmsrBaNsieGES02c+Zqb6aijVtLurkiIimUADyrMzZd0VvCv5AR+G1v+5gGDRUPlpFKoEG6EvzKXgcYAV5ZRiEYTPmr4EDIxAArTO/Ip8mYiu2H6CFSsQEWOerJWwViYYvSwrDogAxQYErADRDnmL2N7NzkQBhADF3brZz13aijEtItsm6hAdWfJEdQstju1cuD3Ka/mSfDT0ZWLxbsC8TVWJ4nTL2niQZGAqT8mtdaEFcdifnKHqeQI/TnBH7tOtdHGR83j0/PhfEAqMdhW1Q3QGq9d6zvvfB1MIciSMlGCWvbasm6cBCfKdgld5up8s5WnXH40mAlBST3U3vqZ/13IiPkAi+iyTMAwoGTfWc1J+jrSHwOFMH+Z6u9vPioGZQHz8hAMTBguGkEaLMeBChzKeARzDvE33EBtkvzG5MkEjG9R5IZpSLElECDe/lbdpWdjOVnIXeYDRf0C91QG0LP8Znlgaes1FvmsOkXoNYJM2osYJRPFjrC84fzi5aYv8v6Gg9HGRAQDhRXMJ2QXHqTfzg29LtLe5JjZLq4hE4Gix4m0GFKlvcW9cbwR0c8v1W4kTZSPqtHPtqbbu2J3ByWFAwdYE+T+YLp6EhKRHsBiGIMo997eIm0=
